plugins {
    id 'org.spongepowered.gradle.plugin' version '2.2.0'
}

group 'com.example'
version '1.0.0'
archivesBaseName = 'MySpongePlugin'

repositories {
    mavenCentral()
    maven { url 'https://repo.spongepowered.org/maven' }
}

dependencies {
    compileOnly 'org.spongepowered:spongeapi:14.0.0-20241229.134205-2'
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}

jar {
    from('src/main/resources') {
        include 'plugin.conf'
    }
}